name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - master       # Deploy to Prod
      - develop      # Deploy to Stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Dynamically assign the environment based on the branch
    environment: ${{ github.ref_name == 'master' && 'prod' || 'stage' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build 

    - name: Sync S3 Bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Invalidate CloudFront Cache
      uses: awact/cloudfront-action@v1
      with:
        distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        paths: "/*"
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
